

services:

  api:
    build:
      context: ../api
      dockerfile: ../docker/api/Dockerfile
    container_name: api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../api:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=task_management
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  app:
    build:
      context: ../app
      dockerfile: ../docker/app/Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ../app:/app
      - /app/node_modules

  mysql:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
